#!/usr/bin/env bash
echo ""
echo ""
echo "****************NOTE****************"
echo "Before first use please make sure the current user is added to the dialout group:"
echo "sudo adduser <current user> dialout"
echo "and perform a reboot:"
echo "sudo reboot"
echo "Installing setservice package is also recommended:"
echo "sudo apt install setserial"
echo "************************************"
echo "For more please refer to the manual: https://mabrobotics.pl/servos/manual"
echo "************************************"

# . /etc/bash_completion