# Action name
name: build

# Here, this action will be enabled on all pushes.
# Modify this to fit your needs.
on:
    push

# Jobs section
jobs:
    # The job that will use the container image you just pushed to ghcr.io
    build:
        runs-on: ubuntu-20.04
        container:
            image: klonyyy/armnoneeabi:2
        steps:
            - uses: actions/checkout@v3
              with:
                submodules: recursive
                # token: ${{ secrets.PAT }}
            - name: build_step
              shell: bash
              run: ./release.sh
            - uses: actions/upload-artifact@v3
              with:
                name: MDtool
                path: build/packages/*
